// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EComPlatform.Models;

public partial class Discount
{
    public int DiscountId { get; set; }

    public int ProductId { get; set; }

    public decimal? Percentage { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual Product Product { get; set; }
}