// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EComPlatform.Models;

public partial class PaymentLog
{
    public int PaymentId { get; set; }

    public int OrderId { get; set; }

    public string Provider { get; set; }

    public string TransactionId { get; set; }

    public string Status { get; set; }

    public string ResponseMessage { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}